### ISSUE TITLE
Broken Image tags

### ISSUE THREAD

**Issue by rishi11** [kakkarjoyesh/CS5610-joyeshk#2]
In your experiments there are image tags which are not working properly Please fix them.

**Comment by kakkarjoyesh** [comment]
I will check those. I checked with couple of searches and it was loading fine. Must be because of caching. I will check it.

**Comment by kakkarjoyesh** [comment]
As per latest discussion, that this issue is being worked upon. So, holding off any furthur investigation on this issue.
