### ISSUE TITLE
Experiments Missing

### ISSUE THREAD

**Issue by rishi11** [kakkarjoyesh/CS5610-joyeshk#3]
Every week you have to perform at-least 5 experiments but this week I cannot see any. Please perform at-lest 5 experiments for this week.

**Comment by kakkarjoyesh** [comment]
Hi Rishi,

I am in the process of updating the experiments. I will be updating them by tomorrow afternoon.
I will take care of it in future.

Thanks.

**Comment by kakkarjoyesh** [comment]
Uploaded the experiments on server as well as committed on githug.
