### ISSUE TITLE
Week 7 : Mongo DB experiments Missing

### ISSUE THREAD

**Issue by rishi11** [kakkarjoyesh/CS5610-joyeshk#5]
Hi I cannot see the MongoDB experiments from your homepage as link to them is broken.

**Comment by kakkarjoyesh** [comment]
I have added the mongodb experiments. I am facing couple of issues in the experiments with few instances of code working fine in local instance of mongo but not on server. So, keeping the ticket open.

**Comment by kakkarjoyesh** [comment]
As discussed, closing the ticket.
